# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d647c9490cec7d47d6b7ed2fc797c5691c82d7d02d2e3ab2d24b650922dfa128b5234482607886b915062a0d7685b905ffef4f8da89e7047c413a28fbb548b59

test:
  secret_key_base: a59133148a29c5d6b8a6603ff9a2aeb0d68179f1ad52bc5b2b96d8e2e8747695ff264b624ff93e1832ed9c8308044f52459b805550242347cd90ff4fa6566642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
